name: Compress Folder

on:
  push:
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has write permission to contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Ensure using Node.js version 18

    - name: Install dependencies
      run: npm install archiver

    - name: Compress folder
      run: |
        echo "const fs = require('fs');
        const archiver = require('archiver');
        
        const folderToCompress = 'published/poetry';
        const outputZip = 'compressed-poetry-folder.zip';
        
        const output = fs.createWriteStream(outputZip);
        const archive = archiver('zip', {
          zlib: { level: 9 } // Sets the compression level
        });
        
        output.on('close', function() {
          console.log(archive.pointer() + ' total bytes');
          console.log('archiver has been finalized and the output file descriptor has closed.');
        });
        
        archive.on('error', function(err) {
          console.error('Error during compression', err);
          process.exit(1);
        });
        
        archive.pipe(output);
        
        archive.directory(folderToCompress, false);
        
        archive.finalize();" > compress.js
        node compress.js

    - name: Commit and push compressed folder
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add compressed-poetry-folder.zip
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Compress published/poetry folder'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi
