name: Compress Folder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zipfile36

    - name: Compress folder
      env:
        FOLDER_TO_COMPRESS: 'your-folder-path'  # Replace with the path to the folder you want to compress
        OUTPUT_ZIP: 'compressed-folder.zip'     # Replace with the desired output zip file name
      run: |
        python -c "
import zipfile
import os

folder_to_compress = os.getenv('FOLDER_TO_COMPRESS')
output_zip = os.getenv('OUTPUT_ZIP')

with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(folder_to_compress):
        for file in files:
            zipf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), folder_to_compress))
        "
    - name: Upload compressed folder
      uses: actions/upload-artifact@v2
      with:
        name: compressed-folder
        path: ${{ env.OUTPUT_ZIP }}