name: Create Zip Archive

on:
  push:
    branches:
      - main

jobs:
  create-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has write permission to contents

    steps:
      - name: Clear GitHub Actions Cache
        run: |
          sudo rm -rf /home/runner/work/_actions

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install archiver

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create zip file
        run: node createZip.js

      - name: Debug Workflow
        run: |
          echo "Listing all files in the workspace:"
          ls -R
          echo "Checking for output directory and files:"
          ls output

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: files-zip
          path: output/files.zip