name: Generate Search Index

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the workflow has write permission to contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Ensure using Node.js version 18

    - name: Install dependencies
      run: npm install cheerio

    - name: Generate search index
      run: node generate-search-index.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add search-index.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m 'Generate search index'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi