name: Generate Poems

on:
  push:
    branches:
      - main

jobs:
  generate_poems:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has write permission to contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run generation script
        run: node generate_images.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Generate poem images'
            git push origin HEAD:main