name: Match Album Tracks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  match-album-tracks:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit and push results

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (latest LTS)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Step 3: (Optional) Install dependencies
      # If you ever use npm packages in your script, uncomment below.
      # - name: Install dependencies
      #   run: npm ci

      # Step 4: Run the matching script (ESM compatible)
      - name: Run Track Matching Script
        run: node match-albums.js

      # Step 5: Commit and Push the result
      - name: Commit and Push Matched Album Durations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add album-track-durations.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update album track durations"
            git push origin main
          fi