name: Process and Extract ZIP File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  process_zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has write permission to contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs -y
          git lfs install

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies
        run: npm install

      - name: Run ZIP processing script
        run: node processZipWorkflow.js

      - name: Commit and push extracted files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Process and extract poetry files from ZIP'
            git push origin HEAD:main
          fi