name: Save Lyrics

on:
  push:
    branches:
      - main

jobs:
  save_lyrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the workflow has write permission to contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Run Puppeteer script
        run: node saveLyrics.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add lyrics.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Save lyrics from Genius'
            git push origin HEAD:main
          fi