name: Scan MP3 Metadata and Extract Covers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-mp3-metadata:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit and push extracted covers and metadata

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install music-metadata fs path

      # Step 4: Extract metadata and covers
      - name: Run MP3 Metadata Script
        run: node scan-mp3.js

      # Step 5: Commit and Push covers and metadata
      - name: Commit and Push Metadata & Covers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add covers mp3-metadata.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update covers and mp3 metadata"
            git push origin main
          fi